#! /usr/bin/env Rscript
utils::setRepositories(ind = 0, addURLs = c(CRAN = "http://cran.us.r-project.org"))
# installing R libraries necessary for MChIP-C analysis
install.packages("remotes", quiet=T)
install.packages("BiocManager", quiet = T)
BiocManager::install(version = '3.15', ask = F,update= F, quiet = T)
library(remotes)
install_version('dplyr','1.0.9',quiet = T, upgrade="never")
install_version('tidyr','1.2.0',quiet = T, upgrade="never")
install_version('readxl','1.4.3',quiet = T, upgrade="never")
install_version('reshape2','1.4.4',quiet = T, upgrade="never")
install_version('ggplot2','3.3.6',quiet = T, upgrade="never")
install_version('GGally','2.1.2',quiet = T, upgrade="never")
install_version('gridExtra','2.3',quiet = T, upgrade="never")
install_version('eulerr','7.0.1',quiet = T, upgrade="never")
install_version('fitdistrplus','1.1-8',quiet = T, upgrade="never")
install_version('PRROC','1.3.1',quiet = T, upgrade="never")
install_version('ranger','0.16.0',quiet = T, upgrade="never")
BiocManager::install('GenomicRanges', version = '3.15', update= F, ask = F, quiet = T)
BiocManager::install('rtracklayer', version = '3.15', update= F, ask = F, quiet = T)
BiocManager::install('dendextend', version = '3.15', update= F, ask = F, quiet = T)
BiocManager::install('dendroextras', version = '3.15', update= F, ask = F, quiet = T)
BiocManager::install('UpSetR', version = '3.15', update= F, ask = F, quiet = T)